tap 'caskroom/cask'

brew 'rbenv'
brew 'ruby-build'
brew 'readline'
brew 'openssl'
brew 'imagemagick'
brew 'postgresql'
brew 'ack'
brew 'httpie'
brew 'lua'
brew 'ffmpeg'
brew 'clang-format'
brew 'swiftlint'
brew 'youtube-dl'
